#baseURL = 'https://gepaeckaufgabe.jetzt/'
baseURL = 'https://gepaeckaufgabe.jetzt'
languageCode = 'de-DE'
title = 'Gepäckaufgabe.jetzt Coaching & Beratung'

[params]
  googleAnalyticsID = "G-MPH7C3M2HN"

